plugins {
    id "com.android.application"
}

android {
    namespace = "xyz.liut.bingwallpaper"
    compileSdk = 36

    buildFeatures {
        buildConfig = true
        resValues = true
    }

    defaultConfig {
        applicationId = "xyz.liut.bingwallpaper"
        minSdk = 21
        targetSdk = 36

        versionCode = rootProject.ext.versionCode
        versionName = rootProject.ext.versionName

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
            resValue "string", "app_name", "@string/app_name_debug"
        }

        release {
            minifyEnabled = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            resValue "string", "app_name", "@string/app_name_release"
        }
    }

    lint {
        disable 'GoogleAppIndexingWarning'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }

}


dependencies {
    //---- test -----
    testImplementation 'org.robolectric:robolectric:4.16'
    testImplementation 'javax.inject:javax.inject:1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test:core:1.7.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    //---- provided -----
    compileOnly "androidx.annotation:annotation:1.9.1"

    //---- compile -----
    implementation fileTree(dir: 'libs', include: ['*.jar'])


}
